### ISSUE TITLE
Is it possible to consolidate `fetch` and `fetchBody`?

### ISSUE THREAD

**Issue by pete-murphy** [rowtype-yoga/purescript-fetch#12]
I might be overlooking something, but I haven't been able to understand why the `"body"` type is fixed to `String` in the `fetch` type definition. If we overload the type to be any `body` that satisfies the `Union input thruIn (HighlevelRequestOptions headers body)` constraint
```diff
  fetch
-   :: forall input output @thruIn thruOut headers
-    . Union input thruIn (HighlevelRequestOptions headers String)
+   :: forall input output @thruIn thruOut headers body
+    . Union input thruIn (HighlevelRequestOptions headers body)
    => Union output thruOut CoreRequest.UnsafeRequestOptions
    => ToCoreRequestOptions input output
    => String
    -> { | input }
    -> Aff Response
```
the implementation still satisfies that type and it seems like that would cover the use cases of `fetchBody`.

**Comment by sigma-andex** [comment]
I think there was some reason for this in the past, but looks like since then we changed the implementation and now its just the same. Do you want to create a PR?
