### ISSUE TITLE
Allow cancellation?

### ISSUE THREAD

**Issue by pete-murphy** [rowtype-yoga/purescript-fetch#13]
Sorry if this has already been discussed, but searching issues for "cancel", "abort", "signal" yields no results.

-----

In `affjax` it's possible to cancel an HTTP request using `killFiber`
```purs
affjaxProgram = do
  fiber <- Aff.launchAff do
    void (Affjax.Web.get ResponseFormat.json url)
  Aff.launchAff_ do
    Aff.killFiber (Exception.error "Cancel request") fiber
```
Translating that to use this library would be something like
```purs
fetchProgram = do
  fiber <- Aff.launchAff do
    void (Fetch.fetch url {})
  Aff.launchAff_ do
    Aff.killFiber (Exception.error "Cancel request") fiber
```
but because there's no `Canceler` set up, the request goes through.

![image](https://github.com/rowtype-yoga/purescript-fetch/assets/26548438/3acf4ef6-3dfb-4579-bf27-85c11be91c6c)

See [minimal example on Try PureScript](https://try.purescript.org/?code=LYewJgrgNgpgBAWQIYEsB2cDuALGAnGAKEJWAAcQ8AXOABQKgjCJPMpoEEAzLgKyQAeAOgBKMAM4U04mADFKwJDSTi4YySGlyFS1hWpxufQUIDqMAEZwVhnv2HmLe9nACiPGAGMaACndcvKgBKZwN-QKEja1UjUJpw7yFXAU8YMioUTWi3FLSMzTi4WRgqT2xs4tLsYiQ7QXoQAHM8JGA4AC52tw9vOABVNBQqQlrjAQbm1rgAXjgwEEI4OC4UC3w4AB4AWlsuISgkCDQyqPnFpbgANxAUMDgfI3szSyFGkrUJKRl5PEUqIV44iyEDwUBCSyM%2B0Ox2wRgA%2BnMFhddkIANYoKBQWSrdZ%2BXLpTJoIT4PCUOAAIgAwkhjjAoHACABHCASKjkoLLHF4YgBKoTFptTrdAK9AZDQi8sr8qazM5LFZrPCbHaQg5HE48RHnJbXW73SplISS8og%2BkAbwAvuCUWqYfCtcjIejMdjFfdkqkCZpiXhSUqqTTUvSmSzxGyOQr8MRTR0ugBlKh4dCNQgx2bk7BUKhkcTtAD0ecBmjIB1S2BAUGYeCEVAAnmQUJ5wDAhE3gHmqOAQOI8wBGcnERToWPCwL9QbDIcYWVI6x1cakybAc7G6XAIA)

It could be nice to have cancellation implemented for `fetch` (using [`AbortController`](https://pursuit.purescript.org/packages/purescript-web-fetch/4.0.1/docs/Web.Fetch.AbortController#t:AbortController)), for parity with `affjax` (which folks seem to be migrating away from since it uses deprecated XHR) and for use with APIs like [`useAff`](https://github.com/purescript-react/purescript-react-basic-hooks/blob/v8.2.0/src/React/Basic/Hooks/Aff.purs#L56-L79) in `react-basic-hooks` that assume ability to cancel, but maybe that is beyond the scope of this library.

(Apologies for opening so many issues 😅! I'd be happy to work on any of those that I've opened if the changes would be welcome.)

**Comment by pete-murphy** [comment]
> it uses deprecated XHR

Checking this, XMLHTTPRequest is _not_ deprecated, not sure where I saw that

**Comment by sigma-andex** [comment]
AbortController is in `fetch-core`.

**Comment by i-am-the-slime** [comment]
@pete-murphy very good point, I implemented this in 

v4.1.0 via https://github.com/rowtype-yoga/purescript-fetch/commit/5148ba42dbdc1d0d6218b32d936e0a8ceb78bcef
