### ISSUE TITLE
Shouldn't Response json attribute be typed more specifically 

### ISSUE THREAD

**Issue by paluh** [rowtype-yoga/purescript-fetch#5]
Thanks a lot for providing the lib!

From my perspective `Foreign` is too generic typing for the `json` property - we lose information here and it is rather misleading for newcomers (it introduces people to `Foreign` as proper type for representing `Json` which is not).

I think that we can provide custom `Json` opaque type or use argonaut-core one. What do you think?

**Comment by i-am-the-slime** [comment]
Is a body guaranteed to be `Json` just because the content-type says so?

**Comment by paluh** [comment]
Isn't `fetch` implementation guaranteeing that we have a `JSON` at hand? I mean do you expect something else from this call:

https://github.com/rowtype-yoga/purescript-fetch-core/blob/main/src/Fetch/Core/Response.js#L51

**Comment by paluh** [comment]
And this is exactly the place where we loose information:

https://github.com/rowtype-yoga/purescript-fetch/blob/main/src/Fetch/Internal/Response.purs#L54

**Comment by sigma-andex** [comment]
> I think that we can provide custom `Json` opaque type or use argonaut-core one. What do you think?

I'd rather not depend on another json library, it could even cause cyclic dependencies. 

While I see your point of making it more obvious by having a `foreign import data Json :: Type`, I don't really see what other benefits that brings. The end user will in most cases probably not handle that anyway because they will be using either yoga-json or argonaut and we loose the compatibility with other libraries that use Foreign and which is more pervasive in the purescript ecosystem. I'm open for discussion though.

**Comment by paluh** [comment]
> I'd rather not depend on another json library, it could even cause cyclic dependencies.

I could say the same about `foreign` dependency - it is present in this lib to actually support typing for `json` function and nothing else ;-)

> (...) and we loose the compatibility with other libraries that use Foreign and which is more pervasive in the purescript ecosystem.

This is pretty generic statement - I don't use `Foreign` to represent `Json` in my programs and I didn't notice that it is pervasive approach in the ecosystem. 

On the other hand I fully understand that you don't want to depend on `argounaut-core` - it is sad story that `Json` type is not a standard per se (maybe a minimal library like `js-json` with only the type and parsing and printing function or something like that) and there is a wide spread use of the `Foreign` type to represent `JSON`.

**Comment by paluh** [comment]
P.S.
> While I see your point of making it more obvious by having a foreign import data Json :: Type, I don't really see what other benefits that brings.

The benefit is just a correct type for a value - I don't have to do `unsafeCoerce` or deal with maybe to get back the `Json` from the `Foreign` value (`Foreign` is possibly something more the `Json`).

**Comment by i-am-the-slime** [comment]
@paluh 
Sounds like a good idea:

Have `js-json` and then have two more small libraries that can go from `JS.JSON -> Argonaut.JSON` and `JS.JSON -> Foreign`, no?

**Comment by i-am-the-slime** [comment]
@paluh Btw I invited you as an owner to the org. Please make any change you think makes the library better, I trust you. I think that's time better spent than writing messages in discussions here 😁
